### ISSUE TITLE
where do both Tux images show

### ISSUE THREAD

**Issue by shoulders** [shoulders/com_qwhelloworld-j3#42]
find out where both icons show

**Comment by shoulders** [comment]
## 16x16 is in show in the top left and is defined by
```xml
<menu link='index.php?option=com_helloworld' img="../media/com_helloworld/images/tux-16x16.png">COM_HELLOWORLD_MENU</menu>
```
![image](https://user-images.githubusercontent.com/319997/96150423-3e081380-0f02-11eb-8ab8-d73d62002759.png)

## also see
```css
.icon-helloworld {background-image: url(../media/com_helloworld/images/tux-16x16.png);}
.icon-48-helloworld {background-image: url(../media/com_helloworld/images/tux-48x48.png);}
.menu-easyblog-16x16 {background: url(../media/com_easyblog/images/easyblog-16x16.png) no-repeat;}
.menu-tux-16x16 {background: url(../media/com_helloworld/images/tux-16x16.png) no-repeat;}
```
- https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_decorations_to_the_backend#Modifying_the_main_entry_file says alter this file to use the 48px version but cleary shows 16x16

## I think
that the 48px icon will be used if the admin template specifies it. if i remove the -48- from the css declartion above, it then displays but only a portion of it becasue the area is only for 16x15
